version: 2
jobs:
  build:
    docker:
      - image: circleci/node:16.13.1
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
      - run: CI=true npm run build
  test:
    docker:
      - image: circleci/node:16.13.1
    steps:
      - checkout
      - run: echo "Testing"
      - run: npm install
      - run: npm test
  sola:
    docker:
      - image: circleci/node:16.13.1
    steps:
      - checkout
      - run: echo "Solaaaaa"
workflows:
  version: 2
  build_test_and_lint:
    jobs:
      - build
      - sola
      - test:
          requires:
            - sola
